services:
  backend:
    build:
      target: production
    environment:
      NODE_ENV: production
    restart: always

  frontend:
    build:
      target: production
    environment:
      NODE_ENV: production
    restart: always

  nginx:
    volumes:
      - ./infra/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./infra/certbot/conf:/etc/letsencrypt:ro
      - ./infra/certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"     # Indispensable pour Certbot
      - "9443:443"  # Votre port externe vers le HTTPS interne
    restart: always



  certbot:
    image: certbot/certbot
    volumes:
      - ./infra/certbot/conf:/etc/letsencrypt
      - ./infra/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet;
        sleep 12h & wait $!;
      done"

