server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        # Tente de servir le fichier, sinon renvoie index.html pour React Router
    }
}